<?php
/*******************************************************************************
 * Copyright (c) 2017.
 * this file created in printing-office project
 * framework: Yii2
 * license: GPL V3 2017 - 2025
 * Author:amintado@gmail.com
 * Company:shahrmap.ir
 * Official GitHub Page: https://github.com/amintado/printing-office
 * All rights reserved.
 ******************************************************************************/

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'لغو',
    'ID'=>'شناسه',
    'Name'=>'نام',
    'Description'=>'توضیحات',
    'Date'=>'زمان',
    'Storage'=>'انبار',
    'Zink Number'=>'شماره زینک',
    'Tiraj'=>'تیراژ',
    'Frame Count'=>'تعداد فریم',
    'Zink Count'=>'تعداد زینک',
    'Dimensions'=>'ابعاد',
    'One Two'=>'یک رو/دورو',
    'Color Count'=>'تعداد رنگ',
    'Five Color'=>'رنگ پنجم',
    'Page Count'=>'تعداد صفحه',
    'Product'=>'کالای مصرفی',
    'Stock'=>'موجودی',
    
    
    
    'Create Sprint'=>'ثبت چاپ',
    'Sprints'=>'اقلام چاپ شده',
    'Update'=>'بروزرسانی',
    'Update {modelClass}: '=>'{modelClass}:بروزرسانی ',
    'Create'=>'ثبت',
    'Create Storage'=>'ثبت انبار',
    'Storages'=>'انبارها',
    'Delete'=>'حذف',
    'Export All'=>'خروجی همه اطلاعات',
    'Create Product'=>'ثبت کالای  مصرفی جدید',
    'Products'=>'لیست کالاهای مصرفی'


];
